version: '3.8'

services:
  web:
    build: .
    command: rails server -b 0.0.0.0
    volumes:
      - .:/my_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=sqlite3:db/development.sqlite3
    user: "user"